### ISSUE TITLE
输入包含非中文字符时,槽位输出会包含#号

### ISSUE THREAD

**Issue by swxnh** [Linear95/bert-intent-slot-detector#2]
![image](https://github.com/Linear95/bert-intent-slot-detector/assets/36731853/1e43e090-b672-499b-8ac5-116cd4ab5a22)
如图,当我输入'我想听badapple'时,返回的槽位中包含#字符

**Comment by Linear95** [comment]
这个是BERT tokenizer的算法导致的，你可以直接把#过滤掉，可以看下这个[解释](https://huggingface.co/learn/nlp-course/chapter6/6?fw=pt)

**Comment by AncatComcup** [comment]
非常感谢
