### ISSUE TITLE
如果不准确能教他吗？

### ISSUE THREAD

**Issue by vedbobo** [Linear95/bert-intent-slot-detector#3]
如果意图不准确，能不能校准。
还有能新增新的意图吗？比如我说”打开客厅的灯“现在意图是"LAUNCH", 这种因该是打开APP类的吧！我想把开灯的分开，另取一种类别，能添加吗？

**Comment by Linear95** [comment]
有对应的训练数据就可以添加新意图和slots

**Comment by vedbobo** [comment]
好的。谢谢！
&nbsp;


钻石眼泪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pengyu ***@***.***&gt;; 
发送时间: 2024年5月6日(星期一) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Linear95/bert-intent-slot-detector] 如果不准确能教他吗？ (Issue #3)














 
有对应的训练数据就可以添加新意图和slots

**Comment by vedbobo** [comment]
> 有对应的训练数据就可以添加新意图和slots

好的，谢谢
